Source :https://towardsdatascience.com/optical-character-recognition-ocr-with-less-than-12-lines-of-code-using-python-48404218cccb

# OCR

### <i>Import libraries

In [175]:
import cv2
import pytesseract
import numpy as np

### <i>Load the image

In [153]:
# img = cv2.imread('color_image2.png') #colored image
# img = cv2.imread('color_image.png') #colored image
# img = cv2.imread('image.png') #table
img = cv2.imread('test_img.png') # text
# img = cv2.imread('j_image.png') #to check the erosion and dilation effect

In [154]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [155]:
# show image on window
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### <i>Color conversion to make it grayscale

In [156]:
# color conversion to gray scle image
gray = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)

In [157]:
gray

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [158]:
# show image on window after color conversion
cv2.imshow('RGB2Gray',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

### <i>Apply threshold

In [159]:
# apply threshold
gray ,img_bin = cv2.threshold(gray,0,255,cv2.THRESH_BINARY | cv2.THRESH_OTSU)

In [160]:
# gray = cv2.threshold(gray,128,255,cv2.THRESH_BINARY)

In [161]:
# img_bin = cv2.threshold(gray,128,255,cv2.THRESH_OTSU)

In [162]:
# thresold value
gray

163.0

In [163]:
# image
img_bin

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [164]:
# show image
cv2.imshow('image',img_bin)
cv2.waitKey(0)
cv2.destroyAllWindows()

### <i>Invert the image to make it binary

In [165]:
# change black background and white text
gray = cv2.bitwise_not(img_bin)

In [166]:
gray

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [167]:
# show image
cv2.imshow('image',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

### <i>Apply below morphological operation to remove noise
    1.0 EROSION
    2.0 DILATION

In [168]:
kernel = np.ones((2,1),np.uint8)

In [169]:
kernel

array([[1],
       [1]], dtype=uint8)

In [170]:
img = cv2.erode(gray,kernel,iterations=1)

In [171]:
# after erosion
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [172]:
img = cv2.dilate(img,kernel,iterations=1)

In [173]:
# after dilation
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### <i>Convert image to text

In [177]:
pytesseract.pytesseract.tesseract_cmd = r'C:\Users\USER\AppData\Local\Tesseract-OCR\tesseract.exe'

In [178]:
out_below = pytesseract.image_to_string(img)

In [179]:
out_below

"Parallax effects consist af several layers that slide over each other. By choosing a background\nimage in the menu item Design the first layer can be set as a fixed image. By inserting the\nwidget Images or the widget Text, a background (photo or monochrome) can be selected, This\nbackground must be created in Jimdo Creator across the entire width of the page and thus\neee ea aur eRe Cae uke cn eR ene\nSea ee iri Ce UNA e Luc eer tcc cate\nbut the parallax effect is quite good.\n\nBesides this parallax type, there is a second, much more elegant parallax. This allows nat only\na parallax or not only that many pictures can be scrolled over a background, but also that\nSe ct uc Ue Cee\nSC enc Me ake Ce CCR oC aun Tac cy\nJimdo widgets or settings, but requires an installation via himl code. If you're interested in\nern emt ain\n\n  \n\x0c"